function export_coastline(varargin)
%EXPORT_COASTLINE  Write coastline.js — the vector land base for the polar map.
%
%   export_coastline()
%   export_coastline('tol', 0.02, 'minspan', 0.1)   % finer / more islands
%
% The Greenland panel is drawn in a polar stereographic projection, where raster
% basemaps are awkward (OpenStreetMap does not publish polar tiles at all). Instead
% the land is drawn as VECTOR polygons, reprojected in the browser by exactly the
% same code that places the float markers — so land and floats cannot end up
% misaligned, and the map needs no tile server.
%
% Coastlines come from the same source as the pipeline's own figures: m_map's
% installed GSHHS data (m_gshhs_i), falling back to m_map's bundled world
% coastline (m_coasts.mat) if GSHHS is not installed.
%
% READ-ONLY with respect to ../pipeline. Writes exactly one file: coastline.js.
%
% Dependency: m_map on the MATLAB path (already required by the pipeline's plots).

opt = struct('lonlim', [-120 60], 'latlim', [50 85], 'tol', 0.05, ...
             'minpts', 4, 'minspan', 0.25);
for k = 1:2:numel(varargin)
    opt.(lower(char(varargin{k}))) = varargin{k+1};
end

site_dir = fileparts(mfilename('fullpath'));
if isempty(site_dir), site_dir = pwd; end

[c, src] = get_coast(opt);
if isempty(c), error('export_coastline:noCoast', ...
        'No coastline source found — is m_map on the MATLAB path?'); end

polys = split_polygons(c, opt);
fprintf('source : %s\n', src);
fprintf('kept   : %d land polygon(s), %d vertices total\n', ...
        numel(polys), sum(cellfun(@(p) size(p,1), polys)));

outfile = fullfile(site_dir, 'coastline.js');
write_js(outfile, polys, src, opt);
d = dir(outfile);
fprintf('wrote %s  (%.0f KB)\n', outfile, d.bytes/1024);
end

% =========================================================================
function [c, src] = get_coast(opt)
% [N x 2] lon/lat coastline, NaN-separated. GSHHS first, bundled world second.
c = [];  src = '';
try
    scratch = figure('Visible', 'off');            % isolate m_map side-effects
    cleanup = onCleanup(@() close(scratch));
    m_proj('lambert', 'long', opt.lonlim, 'lat', opt.latlim);
    tmp = [tempname '.mat'];
    m_gshhs_i('save', tmp);                        % lon/lat, no drawing
    c = pick_coast_field(load(tmp));  delete(tmp)
    if ~isempty(c), src = 'GSHHS intermediate (m_gshhs_i)'; return; end
catch
end
try
    c = pick_coast_field(load('m_coasts.mat'));
    if ~isempty(c), src = 'm_map bundled world coastline (m_coasts.mat)'; end
catch
end
end

function c = pick_coast_field(S)
c = [];
fn = fieldnames(S);
for i = 1:numel(fn)
    v = S.(fn{i});
    if isnumeric(v) && size(v,2) == 2 && size(v,1) > 50, c = v; return; end
end
end

% =========================================================================
function polys = split_polygons(c, opt)
% NaN-separated [lon lat] -> cell array of [lat lon] rings, clipped to the
% window, simplified, and rounded. Tiny slivers are dropped.
lon = c(:,1);  lat = c(:,2);
brk = [0; find(isnan(lon) | isnan(lat)); numel(lon)+1];
polys = {};
for i = 1:numel(brk)-1
    idx = (brk(i)+1):(brk(i+1)-1);
    if numel(idx) < opt.minpts, continue; end
    p = [lat(idx), lon(idx)];
    % keep anything that touches the window (a polygon may extend past it)
    if ~any(p(:,1) >= opt.latlim(1) & p(:,1) <= opt.latlim(2) & ...
            p(:,2) >= opt.lonlim(1) & p(:,2) <= opt.lonlim(2)), continue; end
    % drop specks: islands smaller than minspan degrees across add thousands of
    % polygons and megabytes, and are invisible at this map's scale
    if max(range(p(:,1)), range(p(:,2))*cosd(median(p(:,1)))) < opt.minspan, continue; end
    p = decimate_ring(p, opt.tol);
    if size(p,1) < opt.minpts, continue; end
    polys{end+1} = round(p, 3); %#ok<AGROW>
end
end

function p = decimate_ring(p, tol)
% Drop vertices closer than `tol` degrees to the previous kept one (cheap
% simplification; the first and last vertex are always kept so rings close).
if size(p,1) < 3 || tol <= 0, return; end
keep = false(size(p,1),1);  keep(1) = true;  keep(end) = true;
last = p(1,:);
for i = 2:size(p,1)-1
    if abs(p(i,1)-last(1)) > tol || abs(p(i,2)-last(2)) > tol
        keep(i) = true;  last = p(i,:);
    end
end
p = p(keep,:);
end

% =========================================================================
function write_js(outfile, polys, src, opt)
parts = strings(numel(polys),1);
for i = 1:numel(polys)
    p = polys{i};
    rows = compose('[%.3f,%.3f]', p(:,1), p(:,2));
    parts(i) = "[" + strjoin(rows', ",") + "]";
end
L = strings(0,1);
L(end+1) = "// Vector land polygons for the polar (Greenland) map.";
L(end+1) = "// GENERATED by export_coastline.m — do not edit by hand.";
L(end+1) = "// Source: " + string(src);
L(end+1) = sprintf("// Window: lon [%g %g], lat [%g %g]; simplified %g deg, min island %g deg.", ...
                   opt.lonlim(1), opt.lonlim(2), opt.latlim(1), opt.latlim(2), opt.tol, opt.minspan);
L(end+1) = "// Each ring is [[lat, lon], ...] — Leaflet order, so L.polygon takes it as-is.";
L(end+1) = "const landPolygons = [";
L(end+1) = strjoin(parts', "," + newline);
L(end+1) = "];";
L(end+1) = "";
fid = fopen(outfile, 'w', 'n', 'UTF-8');
if fid < 0, error('export_coastline:write', 'cannot write %s', outfile); end
c = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', L);
end
